'''
# Streamit book properties
stb.set_book_config(menu_title="Love & Terror",
                    menu_icon="🖤",
                    options=[
                            "Love & Terror-A Tale of Love under Taliban Rule",
                            "Preface",
                            "Chapter 1",
                            "Chapter 1",
                            "Chapter 2",
                            "Chapter 3",
                            "Chapter 4",
                            "Chapter 5",
                            "Chapter 6",
                            "Chapter 7",
                            "Chapter 8",
                            "Chapter 9",
                            "Chapter 10",
                            "Chapter 11",
                            ],
                    paths=[
                          "pages/Introduction",
                          "pages/Chapter1.md",
                          "pages/Chapter2",
                          "pages/Chapter3",
                          "pages/Chapter4.md",
                          "pages/Chapter5",
                          "pages/Chapter6",
                          "pages/Chapter7",
                          "pages/Chapter8.md",
                          "pages/Chapter9.md",
                          "pages/Chapter10.md",
                          "pages/Chapter11.md",
                          ],
                    icons=[
                          "",
                          "",
                          "",
                          "",
                          "",
                          "",
                          "",
                          "",
                          "",
                          "",
                          "",
                          "",
                          "",
                          ],
                    save_answers=True,
                    )'''